# Generated by Django 4.0.6 on 2022-07-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThaiFoodSalad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('composition', models.CharField(max_length=400)),
                ('price', models.FloatField(default=0)),
                ('vegan', models.BooleanField(default=False)),
                ('spicy', models.BooleanField(default=False)),
                ('very_spicy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThaiFoodWarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('composition', models.CharField(max_length=400)),
                ('price', models.FloatField(default=0)),
                ('vegan', models.BooleanField(default=False)),
                ('spicy', models.BooleanField(default=False)),
                ('very_spicy', models.BooleanField(default=False)),
            ],
        ),
    ]
