# Generated by Django 4.0.6 on 2022-07-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThaiFoodDessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('composition', models.CharField(max_length=400)),
                ('price', models.FloatField(default=0)),
                ('vegan', models.BooleanField(default=False)),
                ('spicy', models.BooleanField(default=False)),
                ('very_spicy', models.BooleanField(default=False)),
            ],
        ),
    ]
